### ISSUE TITLE
`AttributeError: 'module' object has no attribute 'cv'`.

### ISSUE THREAD

**Issue by ekapaul** [artnc/opencv-page-turner#1]
It looks like my `cv2` package has no `cv` in it.
`AttributeError: 'module' object has no attribute 'cv'` at `detect_face` function, on line 

```
flags=cv2.cv.CV_HAAR_FIND_BIGGEST_OBJECT | cv2.cv.CV_HAAR_DO_ROUGH_SEARCH
```

Any idea?

**Comment by ekapaul** [comment]
Looks like an OpenCV bug 
https://github.com/Itseez/opencv/issues/4603

**Comment by vamsimachavaram** [comment]
i got this error to implement Open cv to face recognition in python any possibility

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    font = cv2.cv.InitFont(cv2.cv.CV_FONT_HERSHEY_SIMPLEX, 1, 1, 0, 1, 1)
AttributeError: 'module' object has no attribute 'cv'

**Comment by artnc** [comment]
Hey Earth! (Pat?) Sorry just noticed this - should be fixed by https://github.com/artnc/opencv-page-turner/commit/5ac78badf0c86f334fd2166374f8290609028ff2
